# Generated by Django 3.2.9 on 2022-12-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_id_alter_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.IntegerField()),
                ('Chat', models.CharField(max_length=6000)),
            ],
        ),
    ]
