# Generated by Django 3.2.9 on 2022-12-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='Subject',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
